services:
  vault:
    image: hashicorp/vault:1.14.1
    ports:
      - "8200-8201:8200-8201"
      - "8125:8125"
    environment:
      - SKIP_SETCAP=true
    volumes:
      - "./config:/vault/config.d:ro"
      - "./certs:/vault/certs:ro"
      - "./vault-logs:/vault/logs:rw"
      - "./vault-store:/vault/file:rw"
    command: server -config /vault/config.d/vault-config.hcl -log-file /vault/logs/ -log-rotate-max-files 5
  gitlab-ce:
    image: gitlab/gitlab-ce:16.2.2-ce.0
    hostname: grumpel.fritz.box
    volumes:
      - G:/Data/gitlab-home/config:/etc/gitlab
      - G:/Data/gitlab-home/logs:/var/log/gitlab
      - G:/Data/gitlab-home/data:/var/opt/gitlab
      - ./certs:/etc/gitlab/ssl:ro
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://grumpel.fritz.box:8443'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = ""
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = ""
        gitlab_rails['smtp_password'] = ""
        gitlab_rails['smtp_domain'] = ""
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        nginx['enable'] = true
        nginx['redirect_http_to_https_port'] = 8080
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab-cert.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/server-key.pem"
    ports:
      - "8022:8022"
      - "8443:8443"
      - "8080:8080"
    shm_size: 256m
networks:
  gitlab:
